# Jekyll workshop template
# based on minima theme https://github.com/jekyll/minima

# Site settings

title: Clean Your Data
description: > 
  Introducing OpenRefine, a power tool for the messy work of evaluating, cleaning, and transforming data. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evanwill.github.io/clean-your-data" # the base hostname & protocol for your site

google_analytics: UA-74844011-1

# Build settings
markdown: kramdown
