# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: Clean Your Data
description: "Introducing OpenRefine, a power tool for the messy work of evaluating, cleaning, and transforming data."
keywords: "OpenRefine, academic workshop, data transformation"

# author settings for cc-by
author: evan will
github_username: evanwill
pub_year: 2019

# add the full url for the github repository
repo: "https://github.com/evanwill/clean-your-data"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://evanwill.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /clean-your-data

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
